Helm3.1 onap sync with cn split repos
OPENAIRINTERFACE/openair-mme pull request #19
Opened 2020-11-05 10:01 UTC by lionelgo

Distribution compat: RHEL8.3

2020-11-05 10:05 UTC, rdefosse requested changes

2020-11-05 10:05 UTC, rdefosse commented on openshift/oai-mme-build-config.yml
> +            ref: "helm3.1-onap-sync-with-cn-split-repos"
Please do not change the reference branch --> keep `develop`.

It should be a local change on your local workspace. not to be pushed.

2020-11-05 10:07 UTC, rdefosse commented on etc/mme_fd.sprint.conf
> -ConnectPeer= "@HSS_FQDN@" { ConnectTo = "@HSS_IP_ADDR@"; No_SCTP ; No_IPv6; Prefer_TCP; No_TLS; port = 3868;  realm = "@REALM@";};
Just for my knowledge. What is the impact of removing the realm in this line?

2020-11-05 10:09 UTC, lionelgo commented on etc/mme_fd.sprint.conf
> -ConnectPeer= "@HSS_FQDN@" { ConnectTo = "@HSS_IP_ADDR@"; No_SCTP ; No_IPv6; Prefer_TCP; No_TLS; port = 3868;  realm = "@REALM@";};
HSS and MME can have different realms, this is what happens actually on OC. This REALM is actually the MME realm.

2020-11-05 10:15 UTC, rdefosse commented on etc/mme_fd.sprint.conf
> -ConnectPeer= "@HSS_FQDN@" { ConnectTo = "@HSS_IP_ADDR@"; No_SCTP ; No_IPv6; Prefer_TCP; No_TLS; port = 3868;  realm = "@REALM@";};
Thx

2020-11-05 10:16 UTC, rdefosse approved these changes

2020-11-05 10:43 UTC, rdefosse commented
@lionelgo 

DsTester failed.

2020-11-18 12:50 UTC, rdefosse commented on src/mme_app/mme_config.h
> +#define MME_CONFIG_STRING_S6A_HSS_REALM    "HSS_REAL"
@lionelgo typo?

2020-11-18 12:51 UTC, rdefosse approved these changes

2020-11-18 12:54 UTC, lionelgo commented on src/mme_app/mme_config.h
> +#define MME_CONFIG_STRING_S6A_HSS_REALM    "HSS_REAL"
Yes Typo, something else no good, I check...

2020-11-18 13:04 UTC, rdefosse commented on src/mme_app/mme_config.h
> +#define MME_CONFIG_STRING_S6A_HSS_REALM    "HSS_REAL"
if CI OK, let's be it...

2020-11-18 14:10 UTC, merged